services:
  - type: web
    name: spirit-prayer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: true
